apiVersion: v1
kind: Pod
metadata:
  name: zap-webswing
  namespace: zap
  labels:
    app: zap
    mode: webswing
spec:
  containers:
    - name: zap-webswing
      image: owasp/zap2docker-stable:2.12.0
      args: ['zap-webswing.sh']
      ports:
        - containerPort: 8080
        - containerPort: 8090