apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: zap-executor
  namespace: testkube
spec:
  executor_type: job
  image: lreimer/testkube-zap-executor:latest
  types:
  - zap/api
  - zap/baseline
  - zap/full
  #contentTypes:
  # - "string"
  # - file-uri
  # - git-file
  # - git-dir
  features:
    - artifacts